services:

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: taskmanagement-sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong@Passw0rd
      - MSSQL_PID=Express
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -C -S localhost -U sa -P YourStrong@Passw0rd -Q \"SELECT 1\" || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s


  taskmanagement.api:
    image: ${DOCKER_REGISTRY-}taskmanagementapi
    build:
      context: .
      dockerfile: src/TaskManagement.Api/Dockerfile
    container_name: taskmanagement-api
    ports:
      - "5000:5000"
      #- "5001:5001"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=TaskManagement;User Id=sa;Password=YourStrong@Passw0rd;TrustServerCertificate=True;
    depends_on:
      - sqlserver
    restart: unless-stopped

  taskmanagement.web:
    image: taskmanagement.web
    build:
      context: .
      dockerfile: web/Dockerfile
    container_name: taskmanagement-web
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_BASE_URL=http://taskmanagement-api:5000
      - NEXT_PUBLIC_APP_NAME=Task Management Console
      - NODE_ENV=production
    depends_on:
      - taskmanagement.api
    restart: unless-stopped

  integration.tests:
    image: mcr.microsoft.com/dotnet/sdk:9.0
    container_name: taskmanagement-tests
    working_dir: /src
    volumes:
      - .:/src
      - nuget_packages:/root/.nuget/packages
    environment:
      ASPNETCORE_ENVIRONMENT: Testing
      ConnectionStrings__DefaultConnection: Server=sqlserver,1433;Database=TaskManagementIntegrationTests;User Id=sa;Password=YourStrong@Passw0rd;TrustServerCertificate=true;MultipleActiveResultSets=true;
      TEST_FILTER: FullyQualifiedName~TasksControllerIntegrationTests
    depends_on:
      sqlserver:
        condition: service_healthy
    profiles:
      - tests
    command: >
      sh -c "dotnet restore tests/TaskManagement.Tests/TaskManagement.Tests.csproj &&
             FILTER_ARG=\"\" &&
             if [ -n \"${TEST_FILTER}\" ]; then FILTER_ARG=\"--filter ${TEST_FILTER}\"; fi &&
             dotnet test tests/TaskManagement.Tests/TaskManagement.Tests.csproj $FILTER_ARG"

volumes:
  sqlserver_data:
  nuget_packages:
