services:

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: taskmanagement-sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong@Passw0rd
      - MSSQL_PID=Express
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P YourStrong@Passw0rd -Q 'SELECT 1' || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5


  taskmanagement.api:
    image: ${DOCKER_REGISTRY-}taskmanagementapi
    build:
      context: .
      dockerfile: src/TaskManagement.Api/Dockerfile
    container_name: taskmanagement-api
    ports:
      - "5000:5000"
      #- "5001:5001"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=TaskManagement;User Id=sa;Password=YourStrong@Passw0rd;TrustServerCertificate=True;
    depends_on:
      - sqlserver
    restart: unless-stopped

  taskmanagement.web:
    image: taskmanagement.web
    build:
      context: .
      dockerfile: web/Dockerfile
    container_name: taskmanagement-web
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_BASE_URL=http://taskmanagement-api:5000
      - NEXT_PUBLIC_APP_NAME=Task Management Console
      - NODE_ENV=production
    depends_on:
      - taskmanagement.api
    restart: unless-stopped


volumes:
  sqlserver_data:
